accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as login_logout_views
from . import views as custom_views

app_name = 'accounts'
urlpatterns = [
    path('login/', login_logout_views.LoginView.as_view(), name='login'),
    path('logout/', login_logout_views.LogoutView.as_view(), name='logout'),
    path('registration/', custom_views.RegistrationView.as_view(), name='registration'),
    path('profile/<slug:slug>/', custom_views.ProfileView.as_view(), name='profile'),
    path('profile/<slug:slug>/edit/', custom_views.ProfileUpdateView.as_view(), name='profile_edit'),
]

balabolka/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from balabolka import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views



app_name = 'blog'
urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('post/<slug:slug>/', views.post_detail, name='post-detail'),
    path('post/<slug:slug>/edit/', views.post_edit, name='post_edit'),
    path('post/change/post_new/', views.post_new, name='post_new'),
    path('<str:category_name>/search/', views.FilteredListsView.as_view(), name='filtered_post'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils.safestring import mark_safe
from django.utils.text import slugify

username_validator = UnicodeUsernameValidator()

class User(AbstractUser):
    username = models.CharField(
        ('Username'),
        max_length=150,
        unique=True,
        validators=[username_validator],
        error_messages={
            'unique': "A user with that username already exists.",
        },
    )
    avatar = models.ImageField(upload_to='accounts/avatars/', null=True, blank=True)
    about_me = models.TextField()
    slug = models.SlugField(max_length=200, unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.username)
        super(User, self).save(*args, **kwargs)

    def get_avatar(self):
        if not self.avatar:
            return '/accounts/avatars/default_no_avatar.png'
        return self.avatar.url

    def avatar_tag(self):
        return mark_safe(f'<img src="{self.get_avatar()}" width=50 height="60">')

    avatar_tag.short_description = 'avatar'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text="Enter password",
    )
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        strip=False,
        help_text="Enter the same password as before, for verification.",
    )

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)

accounts/views.py
from .forms import SignUpForm
from django.urls import reverse
from django.views.generic import FormView
from django.views import generic
from .models import User


class RegistrationView(FormView):
    form_class = SignUpForm
    template_name = 'accounts/registration.html'
    success_url = '/accounts/login/'

    def form_valid(self, form):
        form.save()
        return super(RegistrationView, self).form_valid(form)


class ProfileView(generic.DetailView):
    model = User
    template_name = 'accounts/profile.html'


class ProfileUpdateView(generic.UpdateView):
    model = User
    template_name = 'accounts/profile_edit.html'
    fields = ['avatar', 'first_name', 'last_name', 'email', 'about_me']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('accounts:profile', kwargs={'slug': self.object.slug})

accounts/templates/accounts/base.html
<!doctype  html>
<html  lang="en">

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
<head>
<link  rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"  crossorigin="anonymous">
<title>Django Authentication Example</title>
</head>
<body>
  <div  class="container">
    <div  class="row justify-content-center">
      <div  class="col-4">
      <h1  class="text-center">Авторизация</h1>
      {% block main %}
      {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

accounts/templates/accounts/profile.html
{% extends "blog/base.html" %}
{% block profile %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    A {
        color: #2E2E2E; /* Цвет ссылок */
    }

    A:active {
        color: #2E2E2E; /* Цвет активных ссылок */
    }

    .site-heading > a { color:white;}

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }

    .btn-custom_classic{
        color: #fff;
        background-color: #2E2E2E;
        border-color: #2E2E2E;
    }

    .btn-custom_classic:hover{
        background-color: #2E2E2E;
        border-color: #2E2E2E;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    {% if request.user.is_authenticated %}
                        <a class="btn btn-custom_classic p-2 float-right" href="{% url 'accounts:logout' %}">Log out</a>
                        <a class="btn btn-custom_classic p-2 float-right" href="{% url 'blog:home' %}" style="margin-right:10px;">На главную</a>
                        <a class="btn btn-custom_classic p-2 float-right" href="{% url 'blog:post_new' %}" style="margin-right:10px;">Add post</a>
                    {% else %}
                        <a class="btn btn-custom_classic p-2 float-right" href="{% url 'accounts:registration' %}">Sign up</a>
                        <a class="btn btn-custom_classic p-2 float-right" href="{% url 'accounts:login' %}" style="margin-right:10px;">Sign in</a>
                    {% endif %}
                    <h3 class=" site-heading my-4 mt-3 text-white"> Личный кабинет пользователя</h3>
                </div>
            </div>
        </div>
    </div>
</header>
    <div class="card-body">
        {% if user.avatar %}
            <p><img src="{{ MEDIA_URL }}{{ user.avatar.url }}" width="189" height="255"></p>
        {% else %}
            <p></p>
        {% endif %}
        <h3>Username: {{ user.username }}</h3>
        <h3>Имя: {{ user.first_name }}</h3>
        <h3>Фамилия: {{ user.last_name }}</h3>
        <h3>Почта: {{ user.email }}</h3>
        <h3>О себе: {{ user.about_me }}</h3>
    </div>
{% if request.user.username == user.username %}
    <a class="btn btn-custom_classic" href="{% url 'accounts:profile_edit' user.slug %}">edit</a>
{% endif %}
{% endblock %}

accounts/templates/accounts/profile_edit.html
{% extends 'blog/base.html' %}
{% block profile_editor %}

<header class="masthead">
<div class="overlay"></div>
<div class="container">

    <div class="row">
        <div class=" col-md-8 col-md-10 mx-auto">
            <div class="site-heading">
                {% if request.user.is_authenticated %}
                    <a class="btn btn-custom_classic p-2 float-right" href="{% url 'accounts:logout' %}">Log out</a>
                    <a class="btn btn-custom_classic p-2 float-right" href="{% url 'accounts:profile' user.slug %}" style="margin-right:10px;">Profile</a>
                    <a class="btn btn-custom_classic p-2 float-right" href="{% url 'blog:post_new' %}" style="margin-right:10px;">Add post</a>
                {% else %}
                    <a class="btn btn-custom_classic p-2 float-right" href="{% url 'accounts:registration' %}">Sign up</a>
                    <a class="btn btn-custom_classic p-2 float-right" href="{% url 'accounts:login' %}" style="margin-right:10px;">Sign in</a>
                {% endif %}
                <h3 class=" site-heading my-4 mt-3 text-white"><a href="{% url 'blog:home' %}"> Profile editor </a></h3>
            </div>
        </div>
    </div>
</div>
</header>

{% if request.user.is_authenticated %}
    {% if request.user.username == user.username %}
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
    {% endif %}
{% else %}
    <h1>Страница для вас недоступна</h1>
{% endif %}

{% endblock profile_editor %}

accounts/templates/accounts/registration.html
{% extends  'accounts/registration_base.html' %}
{% load crispy_forms_tags %}

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">

{% block main %}
<div class="card">
<div class="card-body">
<h4 class="card-title"></h4>

<form method="post">
{% csrf_token %}
<input type="hidden" name="next" value="{{ next }}">

{{ form|crispy }}

<button type="submit" class="btn btn-primary btn-block">Зарегистрироваться</button>
</form>
</div>
</div>
{% endblock %}

accounts/templates/accounts/registration_base.html
<!doctype  html>
<html  lang="en">
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
<head>
<link  rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"  crossorigin="anonymous">
<title>Django Authentication Example</title>
</head>
<body>
  <div  class="container">
    <div  class="row justify-content-center">
      <div  class="col-4">
      <h1  class="text-center">Регистрация</h1>
      {% block main %}
      {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>