accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as login_logout_views
from . import views as custom_views

app_name = 'accounts'
urlpatterns = [
    path('login/', login_logout_views.LoginView.as_view(), name='login'),
    path('logout/', login_logout_views.LogoutView.as_view(), name='logout'),
    path('registration/', custom_views.RegistrationView.as_view(), name='registration'),
    path('profile/<slug:slug>/', custom_views.ProfileView.as_view(), name='profile'),
    path('profile/<slug:slug>/edit/', custom_views.ProfileUpdateView.as_view(), name='profile_edit'),
]

balabolka/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from balabolka import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views



app_name = 'blog'
urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('post/<slug:slug>/', views.post_detail, name='post-detail'),
    path('post/<slug:slug>/edit/', views.post_edit, name='post_edit'),
    path('post/change/post_new/', views.post_new, name='post_new'),
    path('<str:category_name>/search/', views.FilteredListsView.as_view(), name='filtered_post'),
]

blog/models.py
from django.db import models
from django.utils.text import slugify
from mptt.models import MPTTModel, TreeForeignKey
# from django.contrib.auth.models import User
from accounts.models import User


STATUS = (
    (0, "Draft"),
    (1, "Publish"),
)


class Category(MPTTModel):
    name = models.CharField(max_length=200, unique=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_posts")
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)


    class Meta():
        ordering = ['-created_on']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f'Comment {self.body} by {self.name}'

blog/forms.py
from .models import Comment, Post
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'body']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'category', 'content']

blog/views.py
from django.http import HttpResponseRedirect
from slugify import slugify
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views import generic
from .models import Post, Category, Comment
from .forms import CommentForm, PostForm
import json


class PostListView(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('created_on')
    template_name = 'blog/index.html'

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        categories = Category.objects.all()
        context['category_list'] = categories
        return context


def post_detail(request, slug):
    template_name = 'blog/post_detail.html'
    post = get_object_or_404(Post, slug=slug)

    comments = post.comments.filter(active=True)
    new_comment = None
    comment_form = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, template_name, context={'post': post,
                                                   'comments': comments,
                                                   'new_comment': new_comment,
                                                   'comment_form': comment_form})


def post_new(request):
    template_name = 'blog/post_edit.html'
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.created_on = timezone.now()
            post.slug = slugify(post.title)
            post.save()
            return redirect('blog:post-detail', slug=post.slug)
    else:
        form = PostForm()
    return render(request, template_name, {'form': form})


def post_edit(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.slug = slug
            post.save()
            return redirect('blog:post-detail', slug=post.slug)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})



class FilteredListsView(generic.ListView):
    template_name = 'blog/category.html'
    queryset = Post.objects.filter(status=1).order_by('created_on')

    def get_context_data(self, **kwargs):
        context = super(FilteredListsView, self).get_context_data(**kwargs)
        categories = Category.objects.all()
        context['category_list'] = categories
        context['posts'] = Post.objects.filter(status=1, category=Category.objects.get(
            name=self.kwargs['category_name'])).order_by('created_on')
        return context

blog/templates/blog/base.html
<!DOCTYPE html>
<html>

    <head>
        <title>Блог "Balabolka"</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
        body {
        font-family: "Roboto", sans-serif;
        font-size: 17px;
        background-color: #fdfdfd;
        }

        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }

        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }

        .masthead {
            background: #000000;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }

        body {
            font-family: "Roboto", sans-serif;
            font-size: 18px;
            background-color: #fdfdfd;
        }

        A {
            color: #2E2E2E; /* Цвет ссылок */
        }

        A:active {
            color: #2E2E2E; /* Цвет активных ссылок */
        }

        .site-heading > a { color:white;}

        .card {
            box-shadow: 0 16px 48px #E3E7EB;
        }

        .btn-custom_classic{
            color: #fff;
            background-color: #2E2E2E;
            border-color: #2E2E2E;
        }

        .btn-custom_classic:hover{
            background-color: #2E2E2E;
            border-color: #2E2E2E;
        }

        </style>



        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}


        {% block profile %}
        <!-- Profile Goes here -->
        {% endblock profile %}

        {% block profile_editor %}
        <!-- Profile Goes here -->
        {% endblock profile_editor %}
        
        {% block post-edit %}
        <!-- Post-edit Goes here -->
        {% endblock post-edit %}

    </body>
</html>

blog/templates/blog/category.html
{% extends "blog/base.html" %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
        link: white
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"><a href="{% url 'blog:home' %}">Блог "Balabolka"</a></h3>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in posts %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} | {{ post.category }} </p>
                    <p class="card-text">{{ post.content|slice:":200" }}</p>
                    <a href="{% url 'blog:post-detail' post.slug  %}" class="btn btn-primary">Читать продолжение &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="p-5 float-right" >
            <h4 class="font-italic">Категории</h4>
            {% for category in category_list %}
                <ul class="list-unstyled mb-0">
                    <li><a href="{% url 'blog:filtered_post' category.name %}" >{{ category.name }}</a></li>
                </ul>
            {% endfor %}
        </div>
    </div>
</div>

{%endblock%}

blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% block content %}
<header class="masthead">
    <div class="overlay"></div>
    <div class="container">

        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    {% if request.user.is_authenticated %}
                        <a class="btn btn-custom_classic p-2 float-right" href="{% url 'accounts:logout' %}">Log out</a>
                        <a class="btn btn-custom_classic p-2 float-right" href="{% url 'accounts:profile' user.slug %}" style="margin-right:10px;">Profile</a>
                        <a class="btn btn-custom_classic p-2 float-right" href="{% url 'blog:post_new' %}" style="margin-right:10px;">Add post</a>
                    {% else %}
                        <a class="btn btn-custom_classic p-2 float-right" href="{% url 'accounts:registration' %}">Sign up</a>
                        <a class="btn btn-custom_classic p-2 float-right" href="{% url 'accounts:login' %}" style="margin-right:10px;">Sign in</a>
                    {% endif %}
                    <h3 class=" site-heading my-4 mt-3 text-white"><a href="{% url 'blog:home' %}"> Блог "Balabolka" </a></h3>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
        {% for category in category_list %}
                <a class="p-2 text-muted" href="{% url 'blog:filtered_post' category.name %}" >{{ category.name }}</a>
        {% endfor %}
    </nav>
    </div>
    <div class="row">
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} | {{ post.category }} </p>
                    <p class="card-text">{{ post.content|slice:":200" }}</p>
                    <a class="btn btn-custom_classic p-2" href="{% url 'blog:post-detail' post.slug  %}">Читать продолжение &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>


{%endblock%}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %} {% block content %}
{% load crispy_forms_tags %}
<header class="masthead">
    <div class="overlay"></div>
    <div class="container">

        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    {% if request.user.is_authenticated %}
                        <a class="btn btn-custom_classic p-2 float-right" href="{% url 'accounts:logout' %}">Log out</a>
                        <a class="btn btn-custom_classic p-2 float-right" href="{% url 'accounts:profile' user.slug %}" style="margin-right:10px;">Profile</a>
                        <a class="btn btn-custom_classic p-2 float-right" href="{% url 'blog:post_new' %}" style="margin-right:10px;">Add post</a>
                    {% else %}
                        <a class="btn btn-custom_classic p-2 float-right" href="{% url 'accounts:registration' %}">Sign up</a>
                        <a class="btn btn-custom_classic p-2 float-right" href="{% url 'accounts:login' %}" style="margin-right:10px;">Sign in</a>
                    {% endif %}
                    <h3 class=" site-heading my-4 mt-3 text-white"><a href="{% url 'blog:home' %}"> Блог "Balabolka" </a></h3>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %}
            {{ post.title }}
            <a class="btn btn-default" href="{% url 'blog:post_edit' slug=post.slug %}">Edit</a>
        {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ post.content | safe }}</p>
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        <h2>{{ comments.count }} comments</h2>

        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.body | linebreaks }}
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Ваш комментарий проходит модерацию
        </div>
        {% else %}
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-custom_classic">Submit</button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block post-edit %}
<header class="masthead">
<div class="overlay"></div>
<div class="container">

    <div class="row">
        <div class=" col-md-8 col-md-10 mx-auto">
            <div class="site-heading">
                {% if request.user.is_authenticated %}
                    <a class="btn btn-custom_classic p-2 float-right" href="{% url 'accounts:logout' %}">Log out</a>
                    <a class="btn btn-custom_classic p-2 float-right" href="{% url 'accounts:profile' user.slug %}" style="margin-right:10px;">Profile</a>
                    <a class="btn btn-custom_classic p-2 float-right" href="{% url 'blog:post_new' %}" style="margin-right:10px;">Add post</a>
                {% else %}
                    <a class="btn btn-custom_classic p-2 float-right" href="{% url 'accounts:registration' %}">Sign up</a>
                    <a class="btn btn-custom_classic p-2 float-right" href="{% url 'accounts:login' %}" style="margin-right:10px;">Sign in</a>
                {% endif %}
                <h3 class=" site-heading my-4 mt-3 text-white"><a href="{% url 'blog:home' %}"> Блог "Balabolka" </a></h3>
            </div>
        </div>
    </div>
</div>
</header>

    <h1>Post editor</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-custom_classic">Save</button>
    </form>


{% endblock %}